name: Action Test

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  action-test:
    name: Action Test
    runs-on: ubuntu-latest
    steps:
      - uses: soumojit28/github-action-test@main
        with:
           MESSAGE: "This Is Void"
